### ISSUE TITLE
Grading notes

### ISSUE THREAD

**Issue by asphaltpanthers** [Xynoci/IS2545_Software_Quality_Assurance#1]
Hello @Xynoci,

Your application looks good. The only issues is there are no doubles or shims in your tests. Please check CourseWeb for your grade.

**Comment by Xynoci** [comment]
Hi @asphaltpanthers 

Thank you for pointing that out. 
Yes, i realized that there's not many functions in my application are returning values after it had been finished, which is not quite TDD and makes it hard to apply doubles. I just inspected the code and added two mocks for one of the test cases [here](https://github.com/Xynoci/IS2545_Software_Quality_Assurance/blob/master/src/test/java/hw2/VisitorListGeneratorTest.java).
